### ISSUE TITLE
Need a better definition of version control

### ISSUE THREAD

**Issue by Zu-shi** [Arizona-15-2/Arizona-15-2.github.io#6]
The current one is definitely wrong.  If you need help formulating a better definition, just ask for help!

**Comment by lmzbonack** [comment]
I have completed this issue and submitted a pull request

**Comment by lnanglin** [comment]
I merged your pull request but I think you should go in again and add a little more explanation as to why it is inferior. and actually, change inferior to superior

**Comment by lmzbonack** [comment]
Re-submitted after moving into proper area.

**Comment by lnanglin** [comment]
pull request merged -- closing issue
